---
title: "Flex Dashboard Homework 4"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(viridis)


instacart_data = 
  library(p8105.datasets)
data("instacart") 

instacart = 
  instacart %>% 
  janitor::clean_names() %>% 
  rename("day" = order_dow, "hour" = order_hour_of_day, "name" = product_name) %>% 
  mutate(
    name = as.factor(name),
    aisle = as.factor(aisle),
    day = as.factor(day)
    ) %>% 
   mutate(day = recode(day,
                   '1' = "monday", 
                   '2' = "tuesday", 
                   '3' = "wednesday", 
                   '4' = "thursday", 
                   '5' = "friday",
                   '6' = "saturday", 
                   '0' = "sunday")) 

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
highest_orders =
 instacart %>% 
  count(name, sort = TRUE) %>% 
  top_n(10) %>% 
  select(name)

inner_join(instacart, highest_orders, by = "name") %>% 
  mutate(name = fct_reorder(name, hour)) %>% 
  plot_ly(y = ~hour, color = ~name, colors = "Dark2", type = "box") %>% 
  layout(yaxis = list(title = "Hour of the Day")) %>% 
  layout(title = "Distribution of Most Frequent Orders by Hour")
```

### Chart B

```{r}
  instacart %>% 
    filter(aisle %in% c("eggs", "lunch meat", "candy chocolate", "lunch meat", "cookies cakes", "fresh vegetables")) %>% 
  group_by(hour, aisle) %>% 
  summarize(n = n()) %>% 
  mutate(aisle = fct_reorder(aisle, hour)) %>% 
  plot_ly(x = ~hour, color = ~aisle, type = "box", colors = "Set2") %>% 
    layout(yaxis = list(title = "Aisles"), (xaxis = list(title = "Hour of the Day"))) %>% 
  layout(title = "Distribution of Aisle Orders by Hour")
```


Column {data-width = 500}
-----------------------------------------------------------------------

### Chart C

```{r}
 instacart %>% 
  count(aisle, sort = TRUE) %>% 
  top_n(10) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
    plot_ly(x = ~aisle, y = ~n, color = ~aisle, colors = "Dark2", type = "bar", mode = "markers") %>% 
    layout(yaxis = list(title = "Count"), (xaxis = list(title = "Aisles"))) %>% 
  layout(title = "Frequency of Orders from the Highest Performing Aisles")

```

### Chart D

```{r}
alc_plot = 
  instacart %>% 
  filter(name %in% c("Chardonnay California", "India Pale Ale", "Pinot Noir", "Brut Sparkling Wine", "Pinot Grigio Wine", "Bud Light Beer Cans", "Blue Ribbon Beer")) %>% 
  group_by(name, day, hour) %>% 
summarize(n = n()) %>% 
  ggplot(aes(x = day, y = hour, color = name)) + geom_violin() + labs(x = "Day of the Week", y = "Hour of the Day", Title = "Distribution of Wine and Beer Purchases by day and hour of week")

ggplotly(alc_plot) %>% 
      layout(yaxis = list(title = "Day of the Week"), (xaxis = list(title = "Hour of the Day"))) %>% 
  layout(title = "Alcohol Orders by Day and Hour")


```

