---
title: "Plotly"
output: html_document
toc: true
toc_float: true
code_folding: hide
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, echo = FALSE}
library(tidyverse)
library(viridis)
library(plotly)
```

```{r, message = FALSE, echo = FALSE}
# install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")
instacart_data = 
  library(p8105.datasets)
data("instacart") 
```

# Let's make some plots !

```{r, echo = FALSE}
set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```


```{r}
nyc_airbnb %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers", 
          color = ~price, alpha = 0.5)
```

# Interactive plot showing airbnb prices in NYC neighborhoods 

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "Set2")
```

# Making a bar chart

First you have to make a specific dataset with what you want the y value to go up to * ex. this is a bar chart with neighborhoods and each of their counts as the y axis 

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

```{r}
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)
```



